inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
  - 'db/**/*'
  - 'config/**/*'
  - 'bin/**/*'
  - 'vendor/**/*'
  - 'lib/**/*'

AsciiComments:
  Enabled: false

Airbnb/OptArgParameters:
  Enabled: false

Metrics/LineLength:
  Max: 200

Airbnb/SimpleModifierConditional:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Airbnb/SimpleUnless:
  Enabled: false
